services:
  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
    expose:
      - 33060
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # CON ANCHORS
      #MYSQL_ROOT_PASSWORD: &password soyUnPassword
      MYSQL_USER: fruta
      MYSQL_PASSWORD:  frutita
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql:3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # CON ANCHORS
      #MYSQL_ROOT_PASSWORD: *password
    networks:
      - internal
      - external
    depends_on:
      mysql: 
        condition: service_healthy 
networks:
  internal: {}
  external: {}
volumes:
  mysqldata: {}
      